### ISSUE TITLE
LCE ISSUE

### ISSUE THREAD

**Issue by DHANDAPANISATTANATHAN** [SSOMENSREPO/LCE#4]
SL,

CHECK AND CLEAR THESE ISSUE ALSO

![lce_17042015](https://cloud.githubusercontent.com/assets/9882142/7201223/7c84011a-e522-11e4-93ac-17cf602ea3cf.png)

**Comment by saradambal** [comment]
AS PER ISSUE #1, ISSUE CAME IF LOGIN INTO THE SAME USERNAME WITH ONE/MORE TABS IN BROWSER.

I CORRECTED MY FORM
ACTUAL ISSUE:
WE CHECKING SESSION IN ALL FORM , WE MISSED IN DB SCRIPT WHICH ARE CALLING BY AJAX
SO NEED TO CHECK WITH EACH AJAX CALL FUNC. FOR ALL FORM.

I DID SAMPLE SESSION FILE FOR AJAX , THAT ONE NEED TO INCLUDE IN ALL DB SCRIPT FORM AND REDIRECT TO LOGIN PAGE IN AJAX SUCCESS FUNCTION
